kind: HardwareProfile
apiVersion: infrastructure.opendatahub.io/v1
metadata:
  name: nvidia-gpu  
  namespace: kueue-tenant-a
spec:
  description: 'Nvidia GPU'
  displayName: 'Nvidia GPU'
  enabled: true
  identifiers:
    - defaultCount: 2
      displayName: CPU
      identifier: cpu
      maxCount: 4
      minCount: 1
      resourceType: CPU
    - defaultCount: 4Gi
      displayName: Memory
      identifier: memory
      maxCount: 32Gi
      minCount: 2Gi
      resourceType: Memory
    - defaultCount: 1
      displayName: Nvidia GPU
      identifier: nvidia.com/gpu
      maxCount: 2
      minCount: 1
      resourceType: Accelerator
  scheduling:
    kueue:
      localQueueName: default
      priorityClass: None
    type: Queue