apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: "true"
    notebooks.opendatahub.io/last-image-selection: minimal-gpu:2025.2
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-size-selection: ""
    opendatahub.io/accelerator-name: ""
    opendatahub.io/accelerator-profile-namespace: ""
    opendatahub.io/connections: ""
    opendatahub.io/hardware-profile-name: nvidia-gpu
    opendatahub.io/hardware-profile-namespace: kueue-tenant-a
    opendatahub.io/hardware-profile-resource-version: "2324555"
    opendatahub.io/image-display-name: Jupyter | Minimal | CUDA | Python 3.12
    opendatahub.io/username: kube:admin
    opendatahub.io/workbench-image-namespace: ""
    openshift.io/description: ""
    openshift.io/display-name: workbench-1gpu-2nd
  creationTimestamp: "2025-11-26T02:17:13Z"
  finalizers:
  - notebook.opendatahub.io/httproute-cleanup
  - notebook.opendatahub.io/referencegrant-cleanup
  - notebook.opendatahub.io/kube-rbac-proxy-cleanup
  generation: 1
  labels:
    app: workbench-1gpu-2nd
    kueue.x-k8s.io/queue-name: default
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: kube-3aadmin
  name: workbench-1gpu-2nd
  namespace: kueue-tenant-a
spec:
  template:
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/kueue-tenant-a/workbench-1gpu-2nd
                              --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.2
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: KF_PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2025.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/kueue-tenant-a/workbench-1gpu-2nd/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: workbench-1gpu-2nd
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/kueue-tenant-a/workbench-1gpu-2nd/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8888/
        - --logtostderr=true
        - --v=10
        - --proxy-endpoints-port=8444
        - --config-file=/etc/kube-rbac-proxy/config-file.yaml
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --auth-header-fields-enabled=true
        - --auth-header-user-field-name=X-Auth-Request-User
        - --auth-header-groups-field-name=X-Auth-Request-Groups
        image: registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:657bc0b43fe2da3211d80dc5085f57dccb451c30b1a254b87b4876745c414d36
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: kube-rbac-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/kube-rbac-proxy
          name: kube-rbac-proxy-config
        - mountPath: /etc/tls/private
          name: kube-rbac-proxy-tls-certificates
      enableServiceLinks: false
      serviceAccountName: workbench-1gpu-2nd
      volumes:
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
      - configMap:
          defaultMode: 420
          name: workbench-1gpu-2nd-kube-rbac-proxy-config
        name: kube-rbac-proxy-config
      - name: kube-rbac-proxy-tls-certificates
        secret:
          defaultMode: 420
          secretName: workbench-1gpu-2nd-kube-rbac-proxy-tls